### ISSUE TITLE
Irina: separation-of-concerns, 3 weeks

### ISSUE THREAD

**Issue by IrinaSing** [HackYourFutureBelgium/class-13-14#277]
> [module repository](_)

**Comment by Lizhen2910** [comment]
@IrinaSing Hi, where is your check-in?

**Comment by IrinaSing** [comment]
Hi @Lizhen2910 ! Here it is. I am sorry for being late.

**Comment by colevandersWands** [comment]
> Not sure /i will finish word-list this week.

No worries about this, as long as you're finding your way around the folder structure and the function roles then you can always finish the coding later

**Comment by IrinaSing** [comment]
### Check-In

#### I Need Help With:
Word-list tests. 
Locally `npm run test:ci` gives good results: 
```js
➜  word-list git:(work-branch) npm run test:ci

> word-list@1.0.0 test:ci
> node --experimental-vm-modules node_modules/.bin/jest

(node:502) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:543) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:537) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  src/logic/is-word.spec.js
 PASS  src/logic/sort-strings.spec.js

Test Suites: 2 passed, 2 total
Tests:       36 passed, 36 total
Snapshots:   0 total
Time:        8.248 s
Ran all test suites.
```

But something fails in check before PR: 
https://github.com/IrinaSing/word-list/runs/2732561006?check_suite_focus=true
I don't understand what.

#### What went well?
Learning how to work with branches better.
#### What went less well?
- Not knowing at first that I have to enable Git Workflows on my fork.
- Problem with end of line: I had to change settings of each file from the CRLF to LF manually to pass the lint check up. I would like to know if there is a way to fix this problem once and forever in VSCode, or at least to fix it at once for all the documents in repository.
- Generally it feels like I missed something for understanding current exercises.

#### Lessons Learned
In progress
### Sunday Prep Work
- Study (pick your favorite links)
  - [js.info: Bubbling & Capturing](https://javascript.info/bubbling-and-capturing) (`event.target`)
  - [js.info: Event Delegation](https://javascript.info/event-delegation)
  - [Gordon: DOM Events](https://www.youtube.com/watch?v=QE1YQnhntgw)
  - [Griffith: JS Event Listeners](https://www.youtube.com/watch?v=EaRrmOtPYTM)
  - [Event Delegation (mosh)](https://programmingwithmosh.com/javascript/javascript-event-bubbling-and-event-delegation/)
  - [Event Delegation (all things JS)](https://www.youtube.com/watch?v=6NMSCh3DJug)
  - [Event Delegation (dcode)](https://www.youtube.com/watch?v=pKzf80F3O0U)
- [Integrate](./integrate) (examples)
  - Event Delegation

**Comment by colevandersWands** [comment]
@IrinaSing , I think that test error is from something wrong in the action file. I just pushed a change that might fix it.  give that a try?

and for the line endings.  does that happen locally and on GitHub? or just in one place?

**Comment by IrinaSing** [comment]
@colevandersWands It passed now 👍 
One more problem was with misspelling:

```
warning: You have a misspelled word: eeee on String (spellcheck/spell-checker) at src/logic/sort-strings.spec.js:61:47:
  59 |     });
  60 |     it("4 items", () => {
> 61 |       const actual = sortStrings(["e", "bbb", "eeee", "ee"], "longest");
     |                                               ^
  62 |       expect(actual).toEqual(["eeee", "bbb", "ee", "e"]);
  63 |     });
  64 |   });
```
I saw that "eeee" is in the list to ignore for a spellchecker, but it did not work.
I just switched off linter for that file. Is there more detailed approach to this?

**Comment by IrinaSing** [comment]
@colevandersWands  

> and for the line endings. does that happen locally and on GitHub? or just in one place?

It appears to me in VSCode, and both local and github checks do not let it pass.
Once I missed a couple of files to make a change to LF and all the files that I did correct were changed back to CRLF.

**Comment by colevandersWands** [comment]
that's a tricky choice.  the easy way is to turn off spell checking for .spec files, which isn't ideal since you do want your test descriptions to be spelled correctly.  otherwise you can disable one line at a time which is tedious. 
the more "correct" solution might be to fix the test case so it passes the linting check. but then you can't use such generic test cases.  

tricky one.  i'd probably go with updating the test

**Comment by IrinaSing** [comment]
@colevandersWands  Isn't it possible to add it to exceptions some way so that it pass? I tried to do via VSCode: add to glossary, ignore - it did not work.

**Comment by IrinaSing** [comment]
Spellchecker is tolerant to  "zzz" and "ee", but not to "eeee". Quite strange.

**Comment by colevandersWands** [comment]
you would need to add exceptions one at a time in the `.eslintrc.json` file.  that's bad practice to add exceptions one at a time as you want to use words.  linting files should be the same across everyone's fork and only updated after group agreement.

"ee" and "eee" are ok because the spellchecker only checks after something is 4 characters or longer.  so that you can use variable names with abreviations - https://github.com/HackYourFutureBelgium/word-list/blob/de1d43fe4974ab479d13b5ca68ca5bdef36fdff5/.eslintrc.json#L77

**Comment by IrinaSing** [comment]
Ok, that's not a good solution. 

As for line endings, may the problem be in the original settings.json file?
https://dev.to/wagslane/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-2c3p

**Comment by colevandersWands** [comment]
nice spot for the line endings in VSCode, I was looking for fixes in the linting configurations and script.  but that's also only fixing it in this repo.  
the VSCode fix is more permanent and consistent

**Comment by IrinaSing** [comment]
But probably it should be done by creator of the repo? 

> Note: This setting will not automatically fix all files in your project that have the wrong line endings! It only applies to new ones. To fix the old ones go through and use the manual method.

It did not help when I did it.

**Comment by IrinaSing** [comment]
If you mean fixing it in VSCode app settings I did not find a permanent solution, only changing each file with the button on the footer.

**Comment by colevandersWands** [comment]
did you try [this](https://qvault.io/clean-code/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf/)?

I'll also keep looking into ways to fix it automatically with the linting

**Comment by IrinaSing** [comment]
Yes, The Quick Fix - was only thing to do in my case. For every single file. It does not change all repository files at once.
As I understood if you add some lines of code to the settings file, than all the newly created files will be ok.

I hope I understand your question right.

**Comment by IrinaSing** [comment]
The error in test results looks like this (if this information is useful): 
```
warning: Delete `␍` (prettier/prettier) at src/procedures/update-list.js:5:3:
  3 | /**
  4 |  * Renders an array of strings as an unordered list into the #list-container element
> 5 |  *
    |   ^
  6 |  * @param {string[]} [toRender=[]] - an array of strings to render into the UI
  7 |  */
  8 | export const updateList = (toRender = []) => {
```

**Comment by colevandersWands** [comment]
that is helpful.  it's coming from the prettier plugin.

**Comment by IrinaSing** [comment]
I forgot to mention that I also tried to change prettier settings on end of the line: at first it was "auto", then "lf" - it did not work.

**Comment by IrinaSing** [comment]
Folder was opened in VSCode via Windows instead of WSL, that caused the problem.

**Comment by IrinaSing** [comment]
Sunday prep work

What is state and why should we care about it?
stepped: take a look through these incremental example projects

**Comment by colevandersWands** [comment]
> I don't understand everything shown in JS30 tutorials.

not a problem at all.  He skims over many topics, each of which could be a full week of study.  The big take-aways from studying the 30 should be an overview of what's possible, and more comfort understanding and refactoring interactive pages.
